#!/bin/bash
sudo yum -y update
sudo yum install -y tomcat
sudo yum install wget
cd/home/ec2-user
aws s3://mucodepipeline/codeprethiv/
java -jar filemanager.jar
sudo chmod +x./install
wget https://aws-mucodepipeline-ap-south-1.s3.ap-south-1.amazonaws.com/latest/install
./install auto
